### ISSUE TITLE
Duplicates after renaming a conference

### ISSUE THREAD

**Issue by prigara** [tech-conferences/javascript-conferences#224]
A couple of weeks ago I changed the spelling of names of a bunch of conferences ([commit](https://github.com/tech-conferences/javascript-conferences/commit/ddf2b0e262502d6db7dbb49e9393084d7e3dbdab)). 
Now all of them are listed twice - with the new name and with the old name.
Not sure if the same happens in the other lists.
@nimzco can you please have a look?
Thanks!

**Comment by nimzco** [comment]
Erf I see. Sorry about that, that's because the backend syncs and create UUIDs based on the name which then create new conferences when renaming them or updating the date. I need to find a better system to fix this. Maybe I'll add generate and the UUID in the JSON files.

In any case, I'll fix this right now, thanks for letting me know.

**Comment by nimzco** [comment]
It's fixed. I've also updated how UUIDs are handled, that should cover most of the cases 🤞

**Comment by prigara** [comment]
Great, thank you! 😀
