### ISSUE TITLE
2018 Calendar

### ISSUE THREAD

**Issue by elbaumpj** [tech-conferences/javascript-conferences#81]
Thanks so much for your work--it's a great resource. Will there be a 2018 calendar? If so, happy to help out with its curation.

**Comment by prigara** [comment]
Thank you! :) Sure! I just don't know any events planned for 2018 yet. But anyway, I will add a new table to the main readme.

**Comment by nimzco** [comment]
Hey @elbaumpj!

We now have the conferences stored as JSON files in the [conference folder](https://github.com/tech-conferences/javascript-conferences/tree/master/conferences). Don't hesitate to suggest a conference if you find one, you can simply create a pull request or an issue to add it to the [2018 list](https://github.com/tech-conferences/javascript-conferences/tree/master/conferences/2018).

The format of a conference is now:
```json
  {
    "name": "",
    "url": "",
    "startDate": "2018-08-17",
    "endtDate": "2018-08-19",
    "city": "",
    "country": "",
    "cfpUrl": "",
    "cfpEndDate": "",
    "twitter": "@twitter_handle",
  }
```

And you will find all the conferences on [confs.tech](https://confs.tech/2018/javascript). 👍🏼

I'll close the issue since it's not an issue anymore 😊
